[package]
org = "itelasoftdevelopment"
name = "user_todos_package"
version = "1.0.3"
distribution = "2201.12.2"
keywords = ["choreo-apim-mediation-policy","choreo-apim-mediation-request-flow","choreo-apim-mediation-response-flow","choreo-apim-mediation-fault-flow"]
